spring:
  config:
    activate:
      on-profile: production
    import:
#      - application-oauth.yml
#      - application-rabbitMQ.yml

  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: ${ORACLE_URL}
    username: ${ORACLE_USER}
    password: ${ORACLE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        default_batch_fetch_size: 500
    database-platform: org.hibernate.dialect.Oracle12cDialect
  cache:
    type: redis
  data:
    redis:
      port: 6379
      host: redis-dplanner
      password:
      repositories:
        enabled: false

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 200MB

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %clr(%5level) [%15.15t] [%X{request_id}] %clr(%-40.40logger{39}){cyan} : %m%n%wEx"
    dateformat: Asia/Seoul
  file:
    name: ./log/dplanner.log
  logback:
    rollingpolicy:
      file-name-pattern: ./log/dplanner.%d{yyyy-MM-dd}-%i.log
      max-file-size: 10MB

expire:
  defaultTime: 60

cloud:
  aws:
    stack:
      auto: false
    region:
      static: ap-northeast-2
    credentials:
      access-key: ${AWS_S3_ACCESSKEY}
      secret-key: ${AWS_S3_SECRETKEY}

    s3:
      bucket : dplanner-resource-server

server:
  port: 8080

