spring:
  config:
    activate:
      on-profile: local
    import:
      - application-oauth.yml
#      - application-rabbitMQ.yml

  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: ${ORACLE_URL}
    username: ${ORACLE_USER}
    password: ${ORACLE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        format_sql: true
        show-sql: true
        default_batch_fetch_size: 500
  cache:
    type: redis
  data:
    redis:
      port: 6379
      host: redis-dplanner
      password:
      repositories:
        enabled: false

expire:
  defaultTime: 60

cloud:
  aws:
    stack:
      auto: false
    region:
      static: ap-northeast-2
    credentials:
      access-key: ${AWS_S3_ACCESSKEY}
      secret-key: ${AWS_S3_SECRETKEY}

    s3:
      bucket : dplanner-resource-server

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %clr(%5level) [%15.15t] [%X{request_id}] %clr(%-40.40logger{39}){cyan} : %m%n%wEx"

server:
  port: 8080