spring:
  config:
    activate:
      on-profile: production
    import:
      - application-oauth.yml
      - application-rabbitMQ.yml

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        default_batch_fetch_size: 500
  cache:
    type: redis
  data:
    redis:
      port: 6379
      host: localhost
      password:
      repositories:
        enabled: false

expire:
  defaultTime: 60

cloud:
  aws:
    stack:
      auto: false
    region:
      static: ap-northeast-2
    credentials:
      access-key: ${AWS_S3_ACCESSKEY}
      secret-key: ${AWS_S3_SECRETKEY}

    s3:
      bucket : dplanner-resource-server

server:
  port: 8080

logging:
  level:
    root: info
