spring:
  config:
    activate:
      on-profile: local
    import:
      - application-oauth.yml
      - application-rabbitMQ.yml

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        format_sql: true
        show-sql: true
        default_batch_fetch_size: 500

cloud:
  aws:
    stack:
      auto: false
    region:
      static: ap-northeast-2
    credentials:
      access-key: ${AWS_S3_ACCESSKEY}
      secret-key: ${AWS_S3_SECRETKEY}

    s3:
      bucket : dplanner-resource-server

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace
server:
  port: 8080