version: '3.1'

services:
  api:
    image: dplanner/api:latest
    container_name: dplanner-green
    ports:
      - '9000:8080'

networks:
  default:
    external:
      name: dplanner-private-network