version: '3.1'

services:
  api:
    image: dplanner/api:latest
    container_name: dplanner-blue
    ports:
      - '9001:8080'
    volumes:
      - /var/log/dplanner:/log

networks:
  default:
    external:
      name: dplanner-private-network
