name: CI

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Extract version from tag
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: make firebase adminsdk json
        run: |
          touch ./dplanner/src/main/resources/dplanner-firebase-adminsdk.json
          echo '${{secrets.FIREBASE}}' > ./dplanner/src/main/resources/dplanner-firebase-adminsdk.json
        shell: bash

      - name: Substitute environment variables PROD
        uses: microsoft/variable-substitution@v1
        with:
          files: ./dplanner/src/main/resources/application-production.yml
        env:
          spring.datasource.url: ${{ secrets.ORACLE_URL }}
          spring.datasource.username: ${{ secrets.ORACLE_USER }}
          spring.datasource.password: ${{ secrets.ORACLE_PASSWORD }}
          cloud.aws.credentials.access-key: ${{secrets.AWS_S3_ACCESSKEY}}
          cloud.aws.credentials.secret-key: ${{secrets.AWS_S3_SECRETKEY}}

      - name: Build with Gradle
        run: |
          cd ./dplanner
          chmod +x ./gradlew
          ./gradlew clean build -x test

      - name: Build Docker image
        run: |
          sudo docker build --no-cache \
            -t dplanner/api:latest \
            -t dplanner/api:${{ steps.version.outputs.VERSION }} \
            -f ./dplanner/deploy/Dockerfile ./dplanner --platform linux/x86_64

      - name: Push Docker image
        run: |
          sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          sudo docker push dplanner/api:latest
          sudo docker push dplanner/api:${{ steps.version.outputs.VERSION }}

      - name: Clean Docker image
        run: |
          sudo docker rmi dplanner/api:latest
          sudo docker rmi dplanner/api:${{ steps.version.outputs.VERSION }}
