name: CI

on:
  push:
    branches: [ "main", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE_VERSION: 'latest'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'


      - name: make oauth.yml
        run: |
          cd ./dplanner/src/main/resources
          touch ./application-oauth.yml
          echo "${{secrets.OAUTH}}" > ./application-oauth.yml
        shell: bash

      - name: make firebase adminsdk json
        run: |
          cd ./dplanner/src/main/resources
          touch ./dplanner-firebase-adminsdk.json
          echo "${{secrets.FIREBASE}}" > ./dplanner-firebase-adminsdk.json
        shell: bash

      - name: Substitute environment variables PROD
        if: contains(github.ref,'main')
        uses: microsoft/variable-substitution@v1
        with:
          files: ./dplanner/src/main/resources/application-production.yml
        env:
          spring.datasource.url: ${{ secrets.DB_URL_PROD }}
          spring.datasource.username: ${{ secrets.DB_USER }}
          spring.datasource.password: ${{ secrets.DB_PASSWORD }}
          cloud.aws.credentials.access-key: ${{secrets.AWS_S3_ACCESSKEY}}
          cloud.aws.credentials.secret-key: ${{secrets.AWS_S3_SECRETKEY}}

      - name: Substitute environment variables DEV
        if: contains(github.ref,'develop')
        uses: microsoft/variable-substitution@v1
        with:
          files: ./dplanner/src/main/resources/application-production.yml
        env:
          spring.datasource.url: ${{ secrets.DB_URL_DEV }}
          spring.datasource.username: ${{ secrets.DB_USER }}
          spring.datasource.password: ${{ secrets.DB_PASSWORD }}
          cloud.aws.credentials.access-key: ${{secrets.AWS_S3_ACCESSKEY}}
          cloud.aws.credentials.secret-key: ${{secrets.AWS_S3_SECRETKEY}}

      - name: debug
        run: |
         cat ./dplanner/src/main/resources/application-production.yml
         cat ./dplanner/src/main/resources/dplanner-firebase-adminsdk.json
         cat ./dplanner/src/main/resources/application-oauth.yml


      
      - name: Build with Gradle
        run: |
          cd ./dplanner
          chmod +x ./gradlew
          ./gradlew clean build

      - name: Build Docker image
        run: sudo docker build --no-cache -t dplanner/api:${{ env.DOCKER_IMAGE_VERSION }} -f ./dplanner/deploy/Dockerfile . --platform linux/x86_64

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: sudo docker push dplanner/api:${{ env.DOCKER_IMAGE_VERSION }}

      - name: Clean Docker image
        run: sudo docker rmi dplanner/api:${{ env.DOCKER_IMAGE_VERSION }}
